src/presentation/utils/format.ts
src/presentation/wallet/send/address-amount.tsx

Please @louisinger  review
It closes #171

Use assetPrecision in address-amount and validate the minimum

---

src/application/background-script.ts

hotfix: revert `onstartup` listener in background script 

---

src/application/backend.ts
src/domain/app.ts

https://twitter.com/mempool/status/1426353527702519821

rename explorer: "mempool.space" -> "liquid.network"

---

src/presentation/components/button-asset.tsx
src/presentation/components/button.tsx
src/presentation/onboarding/seed-confirm/index.tsx
src/presentation/onboarding/seed-reveal/index.tsx
src/presentation/onboarding/select-action/index.tsx
src/presentation/onboarding/wallet-create/index.tsx
src/presentation/onboarding/wallet-restore/index.tsx
src/presentation/onboarding/welcome/index.tsx

Several bug fixes to improve responsiveness.
Bugs divided by commit.
Fixes #240

Responsiveness

---

src/presentation/connect/enable.tsx

Fixes bad layout on connect enable view.
From this:
To this:
@tiero please review.

fixes connect enable view

---

src/application/utils/constants.ts
src/presentation/connect/sign-msg.tsx
src/presentation/connect/sign-pset.tsx
src/presentation/connect/spend.tsx
src/presentation/wallet/send/payment-error.tsx

While fixing the typo on the default error message,  I decided to make it a constant.
@tiero please review.

fixes typo and turns 'Ops, something went wrong...' into a constant

---

public/manifest.json

Please test with different browsers.

remove 'tabs' permission from manifest.json

---

src/inject/marina.ts

fix getNetwork() return definition

---

src/presentation/connect/spend.tsx

Show value in fractional L-BTC instead of satoshis

---

src/inject/marina.ts

throws error if value is negative

---

src/presentation/components/asset-list-screen.tsx
src/presentation/utils/sort.ts
src/presentation/wallet/home/index.tsx

Closes #270 
Sorts list of assets by the following criteria:
- first, if present, a new asset (used in receive list), ticker = Any
- afterwards, if present, featured assets order by L-BTC, USDT and LCAD
- finally, all remaining assets in no particular order
Sorts in the following screens:
- home
- receive (with new asset on top)
- send

Show featured assets first

---

src/presentation/components/asset-list-screen.tsx

fixes capitalization of currentPage

---

src/presentation/components/button-asset.tsx

fixes font width when 0 LBTC

---

package.json
src/content/marinaBroker.ts
src/inject/marina.ts
yarn.lock

fixes #283
sendTransaction no longer return the signed tx hex, now broadcast it and return the transaction id.

Make sendTransaction broadcast the signed transaction

---

src/presentation/components/address-amount-form.tsx

remove maximum number of digits in send form

---

src/application/utils/network.ts
src/presentation/utils/error.ts

raises post to explora error to UI

---

package.json
test/spend.spec.ts
yarn.lock

Related to:
- #293
- https://github.com/vulpemventures/marina-provider/pull/15
- https://github.com/vulpemventures/ldk/pull/105

Return publicKey field in getNext{Change}Address APIs

---

src/content/marina/marinaBroker.ts
src/inject/marina/provider.ts

Fixes #302
This PR:
- validates asset and value on all recipients in sendTransaction()
- moves value validation from provider.ts to marinaBroker.ts

Validate recipient object

---

src/presentation/components/explorer-custom-form.tsx

fix bug where update button was on top of the input box

---

package.json
src/content/marina/marinaBroker.ts
src/inject/marina/provider.ts
yarn.lock

add reloadCoins to API

---

public/manifest.json

replace `unsafe-eval` by `wasm-eval`.

wasm-eval in CSP

---

src/presentation/components/modal-menu.tsx

add small margin right of settings dropdown

---

src/domain/app.ts
src/presentation/settings/explorer.tsx

closes #326 
@tiero what do you mean with "weird behaviour"?

add correct options to explorer dropdown in testnet

---

package.json
src/content/marina/marinaBroker.ts
yarn.lock

Closes #342
@tiero please review.
Looks solid:

Ldk compatible utxos 342

---

src/application/utils/utxos.ts
src/content/marina/marinaBroker.ts
src/inject/marina/provider.ts
src/presentation/wallet/send/end-of-flow.tsx

Closes #341 
When broadcasting a transaction:
- inspects inputs to find own coins and lock them;
- inspects outputs to find change addresses and credit it them.

Marina Web Provider: Broadcast transaction

---

src/content/marina/marinaBroker.ts

Implement the getAccountsIDs provider method

implement marina.getAccountsIDs

---

package.json
src/application/redux/sagas/updater.ts
test/customscript.spec.ts
yarn.lock

allow marina to handle single-leaf templates.

bump ldk 0.5.2

---

src/presentation/wallet/send/address-amount.tsx

fixes bug when going back on send address and amount selection

---

src/domain/app.ts

fix bug with mempool explorer url

---

src/presentation/wallet/send/end-of-flow.tsx
src/presentation/wallet/send/payment-error.tsx

no condition on retry button.
it closes #414 

payment-error page: RETRY button in case of INVALID_PASSWORD_ERROR

---

src/presentation/wallet/send/choose-fee.tsx

choose-fee: logo and balance depends on select asset fee

---

src/application/redux/actions/wallet.ts
src/application/redux/reducers/wallet-reducer.ts
src/content/marina/marinaBroker.ts
src/domain/account.ts
src/domain/customscript-identity.ts
test/customscript.spec.ts

* add optional change template in CustomScriptIdentity
* update CustomScriptAccount
* isSpendableByMarina member is now True if and only if template AND changeTemplate are spendable.
* add 2 tests for changeTemplate
it closes #383 

CustomScript with optional change template

---

src/extension/components/button-transaction.tsx
src/extension/utility/format.ts
tailwind.config.js

Closes #441 
@tiero @louisinger please review
From
To

Don't truncate values on button transaction

---

src/domain/transaction.ts

This PR ensures that we are not adding the burn outputs value to "transfer" amount. 
it closes #444 
@tiero @bordalix please review

skip OP_RETURN scripts while computing transfer

---

src/extension/components/button-asset.tsx
src/extension/utility/format.ts

show zero when there's no balance

---

src/extension/components/address-amount-form.tsx
src/extension/wallet/send/address-amount.tsx

Do not initialize send amount to 0 in `address-amount-form`

---

src/domain/pset.ts

multiply relay fee with 2 (instead of 1.5) as a quick fix to solve fee estimation
related to #473

Quick fix fee estimation

---

package.json
src/application/account.ts
src/application/blinder.ts
src/application/signer.ts
src/application/unblinder.ts
src/application/updater.ts
src/extension/popups/spend.tsx
src/extension/wallet/send/end-of-flow.tsx
test/application.spec.ts
yarn.lock

:warning: this PR is not ready to be merged, it depends on:
TL;DR
* bump to `@ionio-lang/ionio` to `0.4.0` 
* get latest `liquidjs-lib`
* update some `ZKPInterface` types.
@tiero @bordalix @altafan  please review

Update to latest `Ionio`, `liquidjs-lib` and `@vulpemventures/secpk256k1-zkp`

---

src/application/signer.ts
test/application.spec.ts

TL;DR
* `SignerService` will fallback to `input.BIP32Derivation[0]` field to derivate the signing key if `witnessUtxo.script` is unknwown.
* Add a test case signing a simple pset without witnessUtxo.
_Note that the fields `fingerPrint` and `path` are not used because Marina is mapping derivation path to script. Instead this PR uses a trick to re-compute the P2WPKH script from `publicKey` field_. In other words your only need to set up a marina public public in the input to request a signature.
try it yourself: [marina-0.5.4.zip](https://github.com/vulpemventures/marina/files/13033604/marina-0.5.4.zip)

SignerService: request signature using BIP32Derivation field

---

package.json
yarn.lock

bump ionio to `0.5.1` and liquidjs-lib to `6.0.2-liquid.31`

---

package.json
yarn.lock

bump liquidjs-lib to `6.0.2-liquid.32`
bump ionio to `0.5.2`
it closes #498 

update `liquidjs-lib` & `ionio-lang`

---

playwright-tests/injected-script.spec.ts
playwright-tests/popup.spec.ts
src/extension/components/balance.tsx
src/extension/utility/format.ts
src/extension/wallet/home/index.tsx
src/extension/wallet/send/address-amount.tsx
src/extension/wallet/send/choose-fee.tsx
src/extension/wallet/transactions/index.tsx
test/application.spec.ts

closes #503 
- updates several balances in the app
- new tests on application.spec

show balance with spaces

---

src/domain/pset.ts

reduce fee

---

src/pkg/boltz.ts

closes #511 
tested with Boltz team

add referralId to boltz /createswap

---

package.json
src/pkg/boltz.ts
test/boltz.spec.ts
yarn.lock

Pending on https://github.com/ionio-lang/ionio/pull/40
Closes #523 
@altafan please review

Replace OP_NOP2 with OP_CHECKLOCKTIMEVERIFY

---

package.json
yarn.lock

freeze @vulpemventures/secp256k1-zkp to 3.1.0

---

src/pkg/boltz.ts

fix bug with boltz testnet url
