vulpemventures/marina

package.json, src/application/redux/reducers/app-reducer.ts, src/application/redux/reducers/asset-reducer.ts, src/application/redux/reducers/connect-data-reducer.ts, src/application/redux/reducers/index.ts, src/application/redux/reducers/taxi-reducer.ts, src/application/redux/reducers/transaction-reducer.ts, src/application/redux/reducers/txs-history-reducer.ts, src/application/redux/reducers/wallet-reducer.ts
**This PR adds the `version` field to persisted reducers.**
- improve `persist` function type and syntax.
- add the `version` field as a parameter in `persist` (initialized to version 1, the current release is 0). Basically, it's a constant number stored in the reducer.
- the migration strategy is the following: if the rehydrated reducer has a version greater than the one defined in scheme, we'll use the `migrate` function defined in `localStorageConfig`.
- next, we should use [MigrationsManifest](https://github.com/rt2zz/redux-persist/blob/master/docs/api.md#createmigratemigrations-config) to implement custom migration for each version number.
it closes #191 
=> Implement redux-persist versioning 

src/application/redux/containers/end-of-flow.container.ts, src/application/redux/containers/payment-success.container.ts, src/application/utils/transaction.ts, src/presentation/components/balance.tsx, src/presentation/utils/constants.ts, src/presentation/utils/index.ts, src/presentation/wallet/send/end-of-flow.tsx, src/presentation/wallet/send/payment-success.tsx
- the asset's logo link now uses a redux selector to get the right explorer URL.
- the `payment-success` page uses a redux selector to get electrs URL.
it closes #202 
- blindAndSignPset function fix: now the tx blinds the recipient output.
it closes #199 
=> Fix explorer links and blindPset function

package.json, src/application/backend.ts, src/application/broker.ts, src/application/proxy.ts, src/application/redux/selectors/wallet.selector.ts, yarn.lock
**This PR adds several fixes for Firefox**
- Use LDK 0.3.9 = LDK with [new blech32](https://github.com/vulpemventures/blech32/pull/10). We need it because Firefox does not support `asm.js` in content scripts;
- `stringify` and `parse` the `details` member in CustomEvent object (for security reasons, firefox does not handle objects payload in window.dispatchEvent).
PS: Cypress does not support "loadExtension" on firefox browsers. Not really a problem as we run it on chrome only.
it closes #165 
=> Fix Marina X Firefox-based browsers

src/application/utils/transaction.ts, src/presentation/wallet/transactions/index.tsx
- In `transactions.tsx` typo: "Outbound/Inbound" instead of "Amount".
- `getTransfers` function now filters the computed values in order to remove the fee "transfer" in case of swap/tdex/taxi txs.
it closes #198  
=> Do not show the fee output as transaction's outbound

src/application/redux/reducers/index.ts, src/application/utils/transaction.ts, src/background-script.ts
This PR fixes the "Invalid password" problem after browser restart.
Redux persist uses migration schemes to handle reducer versionning. However, the current migration scheme was buggish. it overwrite the persisted state while we restart the browser (Rehydrate step in redux persist).
FIX:
1. merge `state` after `initialState` in migrator redux-persist.
2. before set the popup in `backgroundscript.ts`, we checks if there is an encrypted mnemonic persisted in browser storage. It lets, at least, to redirect to onboarding page if something goes wrong with mnemonic storage.
it closes #79 
=> fix webext-redux migration logic + add a check in "onStartup" listener

package.json, src/application/backend.ts, src/application/marina.ts, src/application/redux/actions/action-types.ts, src/application/redux/actions/connect.ts, src/application/redux/reducers/connect-data-reducer.ts, src/application/utils/transaction.ts, src/domain/app.ts, src/domain/connect.ts, src/presentation/connect/spend.tsx, src/presentation/wallet/send/choose-fee.tsx, src/presentation/wallet/send/end-of-flow.tsx, yarn.lock
This PR implements the new changes introduced by marina-provider 1.4.0.
* `sendTransaction` now accepts a list of recipients, and an optional feeAssetHash parameter.
* if the feeAssetHash is not LBTC, we'll use liquid.taxi to craft a taxi tx.
* `getFeeAssets` returns all the asset accepted as fee (taxiAssets + L-BTC).
* rework and cleaning of `utils/transaction.ts`.
it closes #214 
=> Extend `sendTransaction` and add `getFeeAssets`

package.json, src/application/utils/message.ts, src/presentation/connect/sign-msg.tsx, yarn.lock
This PR returns the public key (hex string) in `marina.signMessage` function. 
it closes #228 
=> Return public key in SignedMessage (marina-provider 1.4.2)

src/application/redux/containers/receive-select-asset.container.ts, src/application/redux/containers/send-select-asset.container.ts, src/application/redux/reducers/asset-reducer.ts, src/domain/assets.ts, src/presentation/components/asset-list-screen.tsx, src/presentation/components/button-asset.tsx, src/presentation/components/button-list.tsx, src/presentation/routes/constants.ts, src/presentation/routes/index.tsx, src/presentation/wallet/home/index.tsx, src/presentation/wallet/receive/receive-select-asset.tsx, src/presentation/wallet/send/select-asset.tsx, src/presentation/wallet/send/send-select-asset.tsx, src/presentation/wallet/transactions/index.tsx
**This PR uses the `AssetListScreen` component from send flow to receive flow in order to add a step before generating wallet addresses**
- abstract the `SelectAsset` screen in order to reuse it in `send-select-asset.tsx` and `receive-select-asset.tsx`.
- add `ButtonList` component (= use the same scrollbar)
- some CSS changes on Home and Transactions views (due to some abstraction in `ButtonList`).
- ATM, the addresses derivation paths do not include the asset type. So all the assets buttons have the same behavior now in `receive-select-asset.tsx`.
it closes #226 
=> Add `ReceiveSelectAsset` page before the address generation

.github/workflows/main.yml, package.json, src/application/redux/actions/connect.ts, src/application/utils/transaction.ts, src/background/backend.ts, src/content/marinaBroker.ts, src/domain/connect.ts, src/presentation/components/address-amount-form.tsx, src/presentation/connect/spend.tsx, src/presentation/wallet/send/choose-fee.tsx, test/_regtest.ts, test/spend.spec.ts, test/test.utils.ts, yarn.lock
* Implement the `data` argument in `sendTransaction` and handle `DataRecipient`: it lets to add an unconfidential OP_RETURN output.
* add `spend.spec.ts` file: test the `creastSendPset` flow mainly.
* use nigiri-github-action in GH CI workflow.
update to marina-provider 1.4.3 (https://github.com/vulpemventures/marina-provider/pull/9)
it closes #231 
=> Implement new `sendTransaction` (with data argument)

src/content/marinaBroker.ts, src/domain/message.ts, src/presentation/connect/sign-msg.tsx, src/presentation/connect/sign-pset.tsx, src/presentation/routes/constants.ts, src/presentation/routes/index.tsx
This PR fixes `sign-pset` popup route (error in name). To avoid making the same mistake later, popup routes are computed via the PopupName type using a new function: `const makeConnectRoute = (popupName: PopupName) => '/connect/${popupName}'`;.
it closes #234 
=> Fix connect popup routes

src/presentation/settings/change-password.tsx, src/presentation/settings/deep-restorer.tsx, src/presentation/settings/explorer.tsx
Some minor fixes on settings pages:
- fixes wrong input label on change password view
- fixes wrong "current page" on deep restorer
- adds same css classes as other subtitles in explorer selector view for coherence
=> Settings fixes

src/inject/proxy.ts
This PR checks if the event received in the proxy is an instance of `Event`. It also reject if undefined.
=> window proxy listener: handle undefined case

src/presentation/connect/spend.tsx
Fixes #256 
Supports up to 3 recipients without overflowing.
With 4 or more recipients it overflows on the y axis (adds scroll bar), see video:
https://user-images.githubusercontent.com/9318412/147461982-5f5e61af-d7a5-4804-9dfc-d383aaf0b10c.mov
How to test: go to https://demo.bitmatrix.app/swap and connect wallet.
=> Many recipients

tailwind.config.js
Fixes #258 
Production build of index.js is now ~3 MB
Tested on Chrome and Firefox (Mac)
=> activates css purge

src/application/redux/reducers/wallet-reducer.ts, src/application/redux/selectors/balance.selector.ts
This PR fixes two regressions:
1. on a new wallet, the first address is now correctly persisted (it closes #263)
2. if a wallet doesn't own any LBTC, a default balance is now added (LBTC = 0)
@tiero @bordalix please review
=> [Hotfix] safe incrementation of address indexes + show default LBTC balance if needed

package.json, tailwind.config.js
Webpack in dev was taking me almost 3 minutes between incremental builds.
I've found the culprit, it was purging the CSS.
This PR makes purge only work on production build.
Webpack incremental builds in dev are now back to under 2 seconds.
=> Fix webpack performance in dev

src/background/background-script.ts, src/presentation/connect/sign-pset.tsx, src/presentation/wallet/log-in/index.tsx
This PR moves the startPeriodicUpdater action from the login page to the background startup listener.
It means that the periodic updater is now launched each time the marina background is started (= each time we open the browser). Note that we do not launch the updater if the user is not onboarded.
it closes #275 
=> Start periodic updater at background startup

src/background/background-script.ts
Fix first click on the extension after install would generate a console error:
- browser.browserAction.openPopup() is only supported on Firefox
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup
=> Fix first click on the extension after install

src/application/redux/containers/transactions.container.ts, src/presentation/wallet/receive/index.tsx, src/presentation/wallet/transactions/index.tsx
Fixes #277
This PR fixes two issues:
1. When going back from Receive the app would crash (see #277 for details)
2. When clicking on Receive from the Asset view the app would always say the mnemonic was not saved
3. Clicking save on the Save Mnemonic modal from step 2 would proceed to Address view
isWalletVerified is now passed as props to Transactions view.
=> Fixes back from Receive

src/background/background-script.ts
After update (extension or browser), the first click on the extension icon wouldn't do anything.
On the backend, the first click would define the popup file, but only open it on the next click.
Related to https://github.com/vulpemventures/marina/pull/282
=> fix first click doing nothing after update

src/domain/address.ts, test/spend.spec.ts
Fixes #301 
This PR:
- Implements a better way to detect if an address is or not confidential
- Adds test for sending a transaction with an unconfidential address
=> Unconfidential address 301

src/application/utils/transaction.ts
This PR:
- fixes error detecting if an input is confidential (unblindData is defined in all inputs after all)
- fixes error that occurred when two inputs were from the same Tx (but with different vouts)
@louisinger @tiero please review
=> Fix input blinding data

package.json, src/application/utils/network.ts, src/content/marina/marinaBroker.ts, src/inject/marina/provider.ts, yarn.lock
fixes #310 
Before merging:
- Accept PR https://github.com/vulpemventures/marina-provider/pull/17
- Bump marina-provider to 1.4.8 (expected new version)
- yarn install and commit new yarn.lock
Additional fixes/improvements:
- [fix correct return type for broadcastTx](https://github.com/vulpemventures/marina/commit/7c634cf196ba5ff37352e1355e205146bb1fc6f5)
- [puts import type in alphabetical order](https://github.com/vulpemventures/marina/commit/072258be2bd863310fb8a25593df64aa6d86a886)
=> Return txid and hex in send transaction 310

src/presentation/connect/enable.tsx, src/presentation/connect/sign-msg.tsx, src/presentation/connect/sign-pset.tsx, src/presentation/connect/spend.tsx
Fixes #314 
This PR:
- Sends response message `false` when user closes the window without answering
- Small code refactor in `src/presentation/connect/enable.tsx`
=> Detect window close

src/background/background-script.ts
Since `browser.windows.create` options doesn't allow `right`, we need
to calculate `left` with window width, popup width, and some margin.
=> Makes popup prompt appear on top right of the screen

package.json, src/content/marina/marinaBroker.ts, yarn.lock
This PR adds support for `ionio-artifact` template (argument in `marina.importTemplate`).
if the template argument in `importTemplates` is `ionio-artifact` marina will try to build a valid descritptor from the artifact functions. Using `toDescriptor` func from @ionio-lang/ionio.
=> support ionio-artifact template type

src/presentation/onboarding/wallet-restore/mnemonic-field.tsx
I was going to add custom error messages for detection of new lines as well since entering a new line between words (without spaces) will register a '\n' as part of the words in the seed phrase, but I'm not sure if that needs to be addressed
This closes: #362
=> [Onboarding] Moved seed validation from onChange event handler to onBlur event handler

src/application/redux/sagas/updater.ts, src/application/utils/marina-event.ts, src/content/marina/marinaBroker.ts, src/content/store-cache.ts
Closes #377
**Bug fixes:**
- fix bug where only the main account was emitting events on `NEW_TX`, `NEW_UTXO` and `SPENT_UTXO`
**Improvements:**
- marina events (see list above) now returns the accountID in the payload
**Breaking changes (marina events):**
- `marina.on('NEW_TX', (tx) => {})` is now `marina.on('NEW_TX', ({ tx, accountID }) => {})`
- `marina.on('NEW_UTXO', (utxo) => {})` is now `marina.on('NEW_UTXO', ({ utxo, accountID }) => {})`
- `marina.on('SPENT_UTXO', (utxo) => {})` is now `marina.on('SPENT_UTXO', ({ utxo, accountID }) => {})`
**Worth mentioning:**
- adds accountID to console.debug when reporting utxos fetched from explorer
@tiero @louisinger please review.
=> Bug fix and improvement on marina events

src/application/redux/actions/wallet.ts, src/application/redux/containers/home.container.ts, src/application/redux/containers/receive-select-asset.container.ts, src/application/redux/containers/transactions.container.ts, src/application/redux/reducers/wallet-reducer.ts, src/application/redux/selectors/wallet.selector.ts, src/application/utils/constants.ts, src/domain/account.ts, src/presentation/utils/sort.ts, src/presentation/wallet/home/index.tsx
* HOTFIX: "CustomScriptData.covenantDescriptors" renamed into "contractTemplate" (has been renamed in former PR but some parts of the code still use the empty "covenantDescriptors" field).
* UI selects only the accounts spendable by marina UI (for balances, utxos and transactions). it closes #374 
=> naming fix + select only spendableByMarina accounts in UI

src/application/redux/reducers/index.ts, src/domain/migrations.ts, test/migrations.spec.ts
* PR #366 renamed `covenantDescriptors` field into `covenantTemplate`
* a fix about variable naming in PR #376 has been published but need a migration to handle renaming in case of the user still have former version of the reducer.
This PR ensures that the wallet reducers with version 3 (master reducer) are migrated to reducer version 4 (rename customScriptAccountData member).
Bonus: add a test for the V2 -> V3 migration
it closes #388 
=> add walletState V4 migration

package.json, src/application/redux/reducers/index.ts, src/domain/migrations.ts, yarn.lock
* bump to LDK 0.5.8
* add a new wallet state (v5) to erase transactions history (in order to re-fetch the whole history).
it closes #393 
it closes #395 
it closes #375 
=> Transaction history fix

src/content/marina/marinaBroker.ts
The following provider functions will use [MainAccountID] parameter if no param has been provided by user:
* getAddresses()
* getCoins()
* getTransactions()
* reloadCoins()
* getBalances() it closes #408 
=> marina provider getters with `undefined` accountsIDs param fallback to [MainAccountID]

src/application/redux/reducers/index.ts, src/domain/account.ts, src/domain/migrations.ts, test/migrations.spec.ts
This PR adds a new wallet state (V6) checking if any zpub, ypub etc... are in wallet reducer and convert them to `xpub...` master public keys.
[marina-0.4.13-xpubhotfix.zip](https://github.com/vulpemventures/marina/files/9608577/marina-0.4.13.zip)
it closes #407
=> add Wallet migration v6 (make sure only xpub are in reducer)

src/application/redux/containers/send-select-asset.container.ts, src/presentation/components/address-amount-form.tsx, src/presentation/components/input.tsx
* refacto the address-amount form (use `Input` component instead of HTLM input)
* add a formik validation rule checking asset precision in amount field
* move the SEND ALL button **above** the amount field (fix weird margin in case of error) -> need ACK on this @tiero 
it closes #406
=> address-amount form: handle asset precision

src/presentation/components/address-amount-form.tsx, src/presentation/components/shell-popup.tsx, src/presentation/routes/guards.tsx, src/presentation/routes/index.tsx, src/presentation/wallet/send/address-amount.tsx, src/presentation/wallet/send/choose-fee.tsx
This PR is reworking the way we memorize the routing logic of send pages.
* drop several `useEffect` handling history.goBack & history.push
* replace useEffect by a new `ProtectedRedirectRoute` applied to homepage (route `/`). That component works like ProtectedRoute but redirect to the right send page depending on the `state.transaction.step` value.
it closes #418 
=> Rework the memorized transaction routing logic

src/presentation/components/buttons-at-bottom.tsx, src/presentation/components/explorer-custom-form.tsx, src/presentation/components/modal-unlock.tsx, src/presentation/connect/create-account.tsx, src/presentation/connect/enable.tsx, src/presentation/connect/sign-msg.tsx, src/presentation/connect/sign-pset.tsx, src/presentation/connect/spend.tsx, src/presentation/settings/change-password.tsx, src/presentation/settings/deep-restorer.tsx, src/presentation/settings/explorer.tsx
Implements new component ButtonsAtBottom that will layout buttons on the following manner:
- 1 button => justify-end
- more then 1 button => justify-between
Uses new ButtonsAtBottom component on:
- src/presentation/components/explorer-custom-form.tsx
- src/presentation/components/modal-unlock.tsx
- src/presentation/connect/create-account.tsx
- src/presentation/connect/enable.tsx
- src/presentation/connect/sign-msg.tsx
- src/presentation/connect/sign-pset.tsx
- src/presentation/connect/spend.tsx
- src/presentation/settings/change-password.tsx
- src/presentation/settings/deep-restorer.tsx
- src/presentation/settings/explorer.tsx (on custom option)
Also:
- Removes button 'Update' on src/presentation/settings/explorer.tsx
Closes #429 
=> Fix inconsistency on buttons layout

src/application/redux/selectors/wallet.selector.ts, src/content/marina/marinaBroker.ts, src/domain/account.ts, src/domain/customscript-identity.ts
This PR improves the way marina provider is generating the account next addresses (getNext*Address functions)
The idea is to **stop restore from state** before generating the next address. Instead we get the last index and generate only that address (the former ones are not used in fact). This improvement lets to have constant execution time for `marina.getNext*Address` call (~25ms whatever the number of addresses in wallet).
it closes #405 (@ErikDeSmedt if u can test on your own app)
=> Improve performance of `marina.getNextAddress`

src/content/marina/marinaBroker.ts
App is calling marina importTemplate like this:
```
await marina.importTemplate({
type: 'ionio-artifact',
template: JSON.stringify(synthAssetArtifact),
})
```
On marina is received by provider, which adds an undefined field to array (`changeTemplate`)
https://github.com/vulpemventures/marina/blob/e91d805c50bc14a8f9ba70511d85f1d7221a5cc8/src/inject/marina/provider.ts#L45-L47
So, params has a length of 2 when the function `importTemplate` is called.
A wrong validation of params[1] on line 493 called `validateContract` with an undefined contract, which generated a throw.
https://github.com/vulpemventures/marina/blob/e08df1c73c53461d94b6434f286766c00c9e6636/src/content/marina/marinaBroker.ts#L485-L499
Changing line 493 to `if (params[1])` fixed it.
The big question is: how did this ever …
=> Fix error when importing template to Marina

package.json, src/extension/settings/networks.tsx, yarn.lock
This PR removes the `sync` calls made in UI and send "restore" messages to background. In other words, the restoration after a network change is made in background.
Bonus: `pkg.json` now fetch `marina-provider` from NPM.
it closes #447 
@bordalix @tiero please review
=> `settings/networks` sends restoreMessage to background

src/extension/wallet/send/address-amount.tsx
it closes #439 
`wallet/send/address-amount` shows the persisted state (address and/or amount set up by the user).
=> correctly load the state in address-amount.tsx form

src/application/utils.ts, src/extension/popups/spend.tsx
I also included a change in utils.ts's `fetchAsset` to explicitly check whether the precision is null or undefined before assigning the default value of 8 because the valid precision value of 0 always falls into the falsy case and can never be set.
Closes #449
=> Added precision to amount formatting in spend.tsx.

src/application/unblinder.ts, src/application/utils.ts, src/background/taxi-updater.ts, src/domain/repository.ts, src/domain/transaction.ts, src/extension/components/button-transaction.tsx, src/extension/components/modal-menu.tsx, src/extension/context/storage-context.tsx, src/extension/wallet/home/index.tsx, src/extension/wallet/transactions/index.tsx, src/infrastructure/storage/common.ts, src/infrastructure/storage/wallet-repository.ts
This PR drops the `useSelectTransactions` hook used in `transactions` view and compute the transactions list from repositories inside the `StorageContext` component. It lets to:
* speed up the transactions list rendering
* speed up the "transfer amount" computing
* be consistent with utxos list (also computed in StorageContext)
the PR also use that newly cached transactions list to filter the asset in `Home` view. it closes #437 
@tiero @bordalix please review this
=> move `useSelectTransations` logic to `StorageContext`

src/background/background-script.ts, src/domain/message.ts, src/extension/components/modal-menu.tsx, src/extension/onboarding/end-of-flow/index.tsx, src/extension/wallet/log-in/index.tsx
This PR ensures that the onboarding/end-of-flow restoration page starts the background services before doing the restoration process (in order to trigger the fetch/unblind tx process).
=> start background services before restore step in `onboarding/end-of-flow` 

.github/workflows/main.yml, .github/workflows/release.yml, manifest/manifest.v2.json, package.json, playwright-tests/utils.ts, webpack.common.js
- `dist` & `web-ext-artifacts` folders are now divided into `v2` & `v3` directories, depending on which version of the extension you are building.
- add a `web-ext:build:v3` script in pkg.json
- `main.yml` CI is now testing v2 AND v3 build & bundle.
- `release.yml` now upload two artifacts: `marina-v3-{version}.zip` & `marina-v2-{version}.zip`.
_Unfortunately it's not possible to run the playwright tests under Firefox cause playwright supports extension context only on Chrome-based browsers._
please @tiero review this
=> Fix manifest v2 extension & release v2 artifact

playwright-tests/injected-script.spec.ts, playwright-tests/utils.ts, src/application/blinder.ts, src/application/presenter.ts, src/application/unblinder.ts, src/application/updater.ts, src/content/marina/marinaBroker.ts, src/domain/presenter.ts, src/domain/pset.ts, src/domain/repository.ts, src/domain/transaction.ts, src/extension/components/button-transaction.tsx, src/extension/popups/sign-pset.tsx, src/infrastructure/storage/wallet-repository.ts, test/application.spec.ts
This PR adds `PsetView` component to `sign-pset.tsx` popup.
Here is an example of a tx spending 2 utxos and sending some L-BTC to my mainAccountTest:
Some changes on others files are related to a duplicate type `UnblindedData`. I've drop the duplicated types and use them from marina-provider. It's only about renaming "txID" to "txid" as defined in `marina-provider`.
it closes #421 
@bordalix @tiero please review
=> Show data about pset to sign inside `marina.signTransaction` popup

src/application/account.ts
If something went wrong during the write operations on repository, no error are thrown due to `Promise.allSettled`. `Promise.all` ensures that an error will be sent in case of marina fails to persist the script.
=> use Promise.all in getNextAddress

playwright-tests/injected-script.spec.ts, playwright-tests/popup.spec.ts, playwright-tests/utils.ts, src/application/presenter.ts, src/domain/transaction.ts, src/extension/popups/sign-pset.tsx, src/extension/wallet/transactions/index.tsx
This PR removes the fee amount from L-BTC inbound/outbound transaction values. In other words, if I send 1 L-BTC + fees, the transactions will be labelled as - 1 L-BTC (fee amount still visible in tx details page).
it closes #483 
@tiero @Janaka-Steph please review
=> Fix and test transaction displaying

playwright-tests/injected-script.spec.ts, playwright-tests/utils.ts, src/content/marina/marinaBroker.ts, src/extension/popups/spend.tsx
This PR is an hotfix of the `spend.tsx` component: a typo error in `fromSatoshi` call was showing only the asset precision. It also adds a playwright test for  `marina.sendTransaction` popup.
it closes #490 
please @tiero review this
[marina-0.5.2-fix-sendTransaction.zip](https://github.com/vulpemventures/marina/files/12356252/marina-0.5.2.zip)
=> `marina.sendTransaction`:  fix amount formatting 

README.md
This PR improves the README file:
- add tests section to readme
- reference to manifest v3 yarn scripts
@altafan @tiero please review
=> add tests section to readme; reference to manifest v3 yarn scripts

src/application/updater.ts, src/domain/repository.ts, src/extension/components/button-transaction.tsx, src/extension/wallet/send/lightning-enter-invoice.tsx, src/infrastructure/storage/refundable-swaps-repository.ts
This PR makes Marina remember previous invoices and don't ask for a submarine swap again.
Implements a new updater strategy for refundable tx (tx from failed swaps):
- these swaps can be in 2 different scenarios:
- they were broadcasted (ie, have a txid)
- remove them if they were swepts by Boltz (not refundable anymore because were spent)
- user didn't went through and didn't broadcasted the tx
- kept in cache cause we can't ask Boltz for another swap with the same invoice, so we will use this values if that happens
- after invoice expiration date these swaps are removed from storage 
Fixes bugs on tx list:
- Wrong 0 
- Refund button was available on tx not confirmed
=> Remembers invoice

src/domain/pset.ts
Closes #516
The problem was fees to low:
- fee estimation was made (too early) with only inputs and outputs for asset to be sent
- afterwards, when adding inputs and outputs to pay fee the transaction would get too large for the fee amount
The solution implemented is to calculate a dummy pset paying fees, get the fee amount for this dummy pset and start counting fee amount for the entire transaction from this value.
=> fixes problem with SEND ALL other assets
